#!/bin/bash

# Run TruffleHog and capture its output
output=$(docker run --rm -v "$PWD:/pwd" trufflesecurity/trufflehog:latest filesystem /pwd)

# Check if any secrets were found
if [[ $output == *"Found verified"* ]]; then # Look for a keyword in the output that indicates a secret was found
    echo "Secrets detected! Push aborted."
    exit 1  # Abort the push
fi
