name: Build and Secure

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Bump Chart.yaml patch version
        run: |
          VERSION=$(grep 'appVersion:' kweather-chart/Chart.yaml | awk '{print $2}')
          BUMPED_VERSION=$(echo "$VERSION" | awk -F. '{print $1"."$2"."($3+1)}')\"
          sed -i "s/appVersion: $VERSION/appVersion: $BUMPED_VERSION/g" kweather-chart/Chart.yaml

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKER_USER }}/kweather:latest,${{ secrets.DOCKER_USER }}/kweather:$BUMPED_VERSION

      - name: Commit updated Chart.yaml
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am "Bump Chart.yaml appVersion to $BUMPED_VERSION [skip-ci]"
          git push
