name: Build and Secure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint

    - name: Static code analysis with pylint
      run: pylint --fail-under=5 weatherutils.py main.py

    - name: Scan dependencies for vulnerabilities
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        format: 'table'
        exit-code: '1' 
        severity: 'CRITICAL,HIGH'
    
    - name: Scan Dockerfile for vulnerabilities
      uses: hadolint/hadolint-action@v2.1.0
      with:
        dockerfile: Dockerfile
        fail-on: warning

    - name: Install cosign
      uses: sigstore/cosign-installer@main

    - name: Generate key pair
      run: cosign generate-key-pair

    - name: Build the Docker image
      run: docker build -t docker.io/jamoos/python-weather-app:latest .

    - name: Scan the Docker image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'docker.io/jamoos/python-weather-app:latest'
        format: 'table'
        exit-code: '1'
        severity: 'CRITICAL' 

    - name: Sign the Docker image
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        cosign sign -key cosign.key docker.io/jamoos/python-weather-app:latest

    - name: Upload public key as artifact
      uses: actions/upload-artifact@v3
      with:
        name: public-key
        path: cosign.pub

    - name: Push Docker image (Optional)
      if: github.ref == 'refs/heads/main' 
      run: |
        docker push docker.io/jamoos/python-weather-app:latest
