name: Build and Secure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install bandit

      - name: Static code analysis with bandit
        run: |
          bandit -r . -f json -o bandit-results.json || true 

      - name: Upload Bandit report
        uses: actions/upload-artifact@v3
        with:
          name: bandit-report
          path: bandit-results.json

      - name: Scan dependencies for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'table'
          exit-code: '1' 
          severity: 'CRITICAL,HIGH'

      - name: Scan Dockerfile for vulnerabilities
        uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: Dockerfile
          fail-on: warning

      - name: Install cosign
        uses: sigstore/cosign-installer@main

      - name: Build and tag the Docker image
        run: docker build -t docker.io/jamoos/python-weather-app:latest .

      - name: Push Docker image
        if: github.ref == 'refs/heads/main' 
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push docker.io/jamoos/python-weather-app:latest

      - name: Get image digest
        id: digest
        run: |
          echo "digest=$(docker images --digests docker.io/jamoos/python-weather-app:latest | awk '{ print $3 }')" >> $GITHUB_OUTPUT

      - name: Sign the Docker image (keyless)
        if: github.ref == 'refs/heads/main'
        run: |
          echo "y" | cosign sign -a GITLAB_OIDC_TOKEN docker.io/jamoos/python-weather-app@${{ steps.digest.outputs.digest }}
