name: Build and Secure

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Bump Chart.yaml patch version
        uses: mikefarah/yq@master
        with:
          cmd: 'yq e ".appVersion = .appVersion | split(".") | .[0] + "." + .[1] + "." + (.[2] | tonumber + 1)" -i kweather-chart/Chart.yaml'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest,${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:$(yq e '.appVersion' kweather-chart/Chart.yaml)

      - name: Commit updated Chart.yaml
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am "Bump Chart.yaml appVersion to $(yq e '.appVersion' kweather-chart/Chart.yaml) [skip-ci]"
          git push
